# See https://docs.docker.com/compose/compose-file/
version: '3'

services:
  programaker-router:
    build: ../router
    ports:
      - 8080:80
    links:
      - programaker-frontend
      - programaker-backend-0:programaker-backend
    environment:
      - FRONTEND_NODE=programaker-frontend
      - FRONTEND_PORT=80
      - BACKEND_NODE=programaker-backend
      - BACKEND_PORT=8888

  programaker-frontend:
    build: ../../frontend

  programaker-backend-0:
    build: ../../backend
    hostname: programaker-backend-0
    ports:
      - 8888:8888
    volumes:
      - programaker-dev-backend-mnesia-0:/app/mnesia
    environment:
      - "NODE_NAME_SUFFIX="
      - "NODE_WITH_HOSTNAME=1"
      - "AUTOMATE_SYNC_PRIMARY=backend@programaker-backend-0"
      - "AUTOMATE_SYNC_PEERS=backend@programaker-backend-0,backend@programaker-backend-1,backend@programaker-backend-2"
      - "MNESIA_DIR=/app/mnesia"

  programaker-backend-1:
    build: ../../backend
    hostname: programaker-backend-1
    ports:
      - 8889:8888
    volumes:
      - programaker-dev-backend-mnesia-1:/app/mnesia
    environment:
      - "NODE_NAME_SUFFIX="
      - "NODE_WITH_HOSTNAME=1"
      - "AUTOMATE_SYNC_PRIMARY=backend@programaker-backend-0"
      - "AUTOMATE_SYNC_PEERS=backend@programaker-backend-0,backend@programaker-backend-1,backend@programaker-backend-2"
      - "MNESIA_DIR=/app/mnesia"

  programaker-backend-2:
    build: ../../backend
    hostname: programaker-backend-2
    ports:
      - 8890:8888
    volumes:
      - programaker-dev-backend-mnesia-2:/app/mnesia
    environment:
      - "NODE_NAME_SUFFIX="
      - "NODE_WITH_HOSTNAME=1"
      - "AUTOMATE_SYNC_PRIMARY=backend@programaker-backend-0"
      - "AUTOMATE_SYNC_PEERS=backend@programaker-backend-0,backend@programaker-backend-1,backend@programaker-backend-2"
      - "MNESIA_DIR=/app/mnesia"


volumes:
  programaker-dev-backend-mnesia-0:
  programaker-dev-backend-mnesia-1:
  programaker-dev-backend-mnesia-2:

networks:
    default:
        external:
          name: programaker-dev-3-nodes
