image: docker:latest

variables:
  DOCKER_IMAGE_ADDONS: plaza-core-addons
  DOCKER_IMAGE_FRONTEND: plaza-core-frontend
  DOCKER_IMAGE_BACKEND: plaza-core-backend
  DOCKER_IMAGE_BACKEND_TEST: plaza-core-backend-test
  DOCKER_BACKEND_CI_BASE: plazaproject/ci-base-backend:52db1adcf019a16a12fd9fe4d6c1c2534d68b561

services:
  - docker:dind

build-addons:
  stage: build
  # tags:
  #   - javascript
  #   - browser-addon
  script:
    - docker build -t "$DOCKER_IMAGE_ADDONS" addons
    - docker run -i --rm -v `pwd`/addons:/app "$DOCKER_IMAGE_ADDONS"

build-frontend:
  stage: build
  # tags:
  #   - javascript
  #   - frontend
  before_script:
    - cd frontend
  script:
    - docker build -t "$DOCKER_IMAGE_FRONTEND" -f scripts/ci-partial.dockerfile .

build-backend:
  stage: build
  # tags:
  #   - erlang
  #   - backend
  before_script:
    - cd backend
  script:
    - docker build -t "$DOCKER_IMAGE_BACKEND" -f scripts/ci-partial.dockerfile .

test-backend-code:
  stage: test
  # tags:
  #   - erlang
  #   - backend
  #   - unit-tests
  dependencies:
    - build-backend
  before_script:
    - cd backend
  script:
    - docker build --cache-from "$DOCKER_BACKEND_CI_BASE" -t "$DOCKER_IMAGE_BACKEND_TEST" -f scripts/ci-partial.dockerfile .
    - docker run -t --rm "$DOCKER_IMAGE_BACKEND_TEST" rebar3 eunit
