image: docker:latest

variables:
  DOCKER_IMAGE_FRONTEND: plaza-core-frontend
  DOCKER_IMAGE_BACKEND: plaza-core-backend
  DOCKER_BACKEND_CI_BASE: plazaproject/ci-base-backend:52db1adcf019a16a12fd9fe4d6c1c2534d68b561

services:
  - docker:dind

build-frontend:
  stage: build
  script:
    - docker build --pull -t "$DOCKER_IMAGE_FRONTEND" frontend

build-backend:
  stage: build
  script:
    - docker pull "$DOCKER_BACKEND_CI_BASE"
    - docker build --cache-from "$DOCKER_BACKEND_CI_BASE" -t "$DOCKER_IMAGE_BACKEND" backend
