image: docker:latest

variables:
  DOCKER_IMAGE_FRONTEND: plaza-core-frontend
  DOCKER_IMAGE_BACKEND: plaza-core-backend

services:
  - docker:dind

build-frontend:
  stage: build
  script:
    - docker build --pull -t "$DOCKER_IMAGE_FRONTEND" frontend

build-backend:
  stage: build
  script:
    - docker build --pull -t "$DOCKER_IMAGE_BACKEND" backend
