image: docker:latest

stages:
  - build
  - test
  - push-commit
  - push-branch  # To avoid duplicating the upload do it sequentially

variables:
  DOCKER_IMAGE_ADDONS: plaza-core-addons
  DOCKER_IMAGE_FRONTEND: plaza-core-frontend
  DOCKER_IMAGE_BACKEND: plaza-core-backend
  DOCKER_IMAGE_BACKEND_TEST: plaza-core-backend-test
  DOCKER_BACKEND_CI_BASE: plazaproject/ci-base-backend:52db1adcf019a16a12fd9fe4d6c1c2534d68b561

services:
  - docker:dind

## Frontend
build-frontend:
  stage: build
  before_script:
    - mkdir -p tmp_docker_images/ || true
    - cd frontend
  artifacts:
    paths:
      - tmp_docker_images/
  script:
    - docker build -t "$CI_REGISTRY"/plaza-project/plaza-core/frontend:$CI_COMMIT_SHA -f scripts/ci-partial.dockerfile .
    - docker save "$CI_REGISTRY"/plaza-project/plaza-core/frontend:$CI_COMMIT_SHA -o ../tmp_docker_images/frontend.tar

push-frontend:
  stage: push-commit
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/frontend.tar
    - cd frontend
  script:
    - docker push "$CI_REGISTRY"/plaza-project/plaza-core/frontend:$CI_COMMIT_SHA
  only:
    - develop
    - master
    - push-docker-images-on-ci # TODO: Remove

tag-frontend-branch:
  stage: push-branch
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/frontend.tar
    - cd frontend
  script:
    - docker tag "$CI_REGISTRY"/plaza-project/plaza-core/frontend:$CI_COMMIT_SHA "$CI_REGISTRY"/plaza-project/plaza-core/frontend:$CI_COMMIT_REF_NAME
    - docker push "$CI_REGISTRY"/plaza-project/plaza-core/frontend:$CI_COMMIT_REF_NAME
  only:
    - develop
    - master
    - push-docker-images-on-ci # TODO: Remove

## Backend
build-backend:
  stage: build
  artifacts:
    paths:
      - tmp_docker_images/
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - mkdir -p tmp_docker_images/ || true
    - cd backend
  script:
    - docker build -t "$CI_REGISTRY"/plaza-project/plaza-core/backend:$CI_COMMIT_SHA -f scripts/ci-partial.dockerfile .
    - docker save "$CI_REGISTRY"/plaza-project/plaza-core/backend:$CI_COMMIT_SHA -o ../tmp_docker_images/backend.tar

test-backend:
  stage: test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/backend.tar
    - cd backend
  script:
    - docker run -t --rm "$CI_REGISTRY"/plaza-project/plaza-core/backend:$CI_COMMIT_SHA rebar3 eunit

dialyze-backend:
  stage: test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/backend.tar
    - cd backend
  script:
    - docker run -t --rm "$CI_REGISTRY"/plaza-project/plaza-core/backend:$CI_COMMIT_SHA rebar3 dialyzer

push-backend:
  stage: push-commit
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/backend.tar
    - cd backend
  script:
    - docker push "$CI_REGISTRY"/plaza-project/plaza-core/backend:$CI_COMMIT_SHA
  only:
    - develop
    - master
    - push-docker-images-on-ci # TODO: Remove

tag-backend-branch:
  stage: push-branch
  dependencies:
    - build-backend
    - push-backend  # To avoid duplicating the upload do it sequentially
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/backend.tar
    - cd backend
  script:
    - docker tag "$CI_REGISTRY"/plaza-project/plaza-core/backend:$CI_COMMIT_SHA "$CI_REGISTRY"/plaza-project/plaza-core/backend:$CI_COMMIT_REF_NAME
    - docker push "$CI_REGISTRY"/plaza-project/plaza-core/backend:$CI_COMMIT_REF_NAME
  only:
    - develop
    - master
    - push-docker-images-on-ci # TODO: Remove
