image: docker:latest

stages:
  - build
  - test

variables:
  DOCKER_IMAGE_ADDONS: plaza-core-addons
  DOCKER_IMAGE_FRONTEND: plaza-core-frontend
  DOCKER_IMAGE_BACKEND: plaza-core-backend
  DOCKER_IMAGE_BACKEND_TEST: plaza-core-backend-test
  DOCKER_BACKEND_CI_BASE: plazaproject/ci-base-backend:52db1adcf019a16a12fd9fe4d6c1c2534d68b561

services:
  - docker:dind

check-build-frontend:
  stage: build
  before_script:
    - cd frontend
  script:
    - docker build -t "$DOCKER_IMAGE_FRONTEND" -f scripts/ci-partial.dockerfile .
  except:
    - develop
    - master
    - push-docker-images-on-ci

build-frontend:
  stage: build
  before_script:
    - cd frontend
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY"/plaza-project/plaza-core/frontend:$CI_COMMIT_SHA -f scripts/ci-partial.dockerfile .
    - docker push "$CI_REGISTRY"/plaza-project/plaza-core/frontend:$CI_COMMIT_SHA
  only:
    - develop
    - master
    - push-docker-images-on-ci

build-backend:
  stage: build
  before_script:
    - cd backend
  script:
    - docker build -t "$DOCKER_IMAGE_BACKEND" -f scripts/ci-partial.dockerfile .
  except:
    - push-docker-images-on-ci

test-backend-code:
  stage: test
  dependencies:
    - build-backend
  before_script:
    - cd backend
  script:
    - docker build --cache-from "$DOCKER_BACKEND_CI_BASE" -t "$DOCKER_IMAGE_BACKEND_TEST" -f scripts/ci-partial.dockerfile .
    - docker run -t --rm "$DOCKER_IMAGE_BACKEND_TEST" rebar3 eunit
  except:
    - push-docker-images-on-ci

dialyze-backend-code:
  stage: test
  dependencies:
    - build-backend
  before_script:
    - cd backend
  script:
    - docker build --cache-from "$DOCKER_BACKEND_CI_BASE" -t "$DOCKER_IMAGE_BACKEND_TEST" -f scripts/ci-partial.dockerfile .
    - docker run -t --rm "$DOCKER_IMAGE_BACKEND_TEST" rebar3 dialyzer
  except:
    - push-docker-images-on-ci
