image: docker:19.03.5-dind

stages:
  - test
  - build
  - e2e-test
  - push-commit
  - push-branch  # To avoid duplicating the upload do it sequentially

variables:
  DOCKER_IMAGE_FRONTEND: programaker-core-frontend
  DOCKER_IMAGE_BACKEND: programaker-core-backend
  DOCKER_IMAGE_BACKEND_OPTIMIZED: programaker-core-backend-optimized

services:
  - docker:19.03.5-dind

## Frontend
test-frontend-logic:
  stage: test
  before_script:
    - cd frontend
  script:
    - docker build --target builder --build-arg BUILD_COMMAND=test-logic -f scripts/ci-partial.dockerfile .

test-frontend-on-browser:
  stage: test
  before_script:
    - cd frontend
  script:
    - docker build -t browser-test -f scripts/browser-test-ci-partial.dockerfile .
    - docker run -v `pwd`:/app --rm -e BROWSER_BIN="chromium-browser" -e BROWSER_OPTS="--no-sandbox" browser-test sh -- /app/scripts/run-browser-tests.sh


build-prod-frontend:
  stage: build
  before_script:
    - mkdir -p tmp_docker_images/ || true
    - cd frontend
  needs: []
  artifacts:
    paths:
      - tmp_docker_images/
    expire_in: 24h # No need to keep it around
  script:
    - docker build -t $DOCKER_IMAGE_FRONTEND -f scripts/ci-partial.dockerfile .
    - docker save $DOCKER_IMAGE_FRONTEND -o ../tmp_docker_images/frontend.tar

push-frontend:
  stage: push-commit
  needs:
    - build-prod-frontend
    - test-frontend-logic
    - test-frontend-on-browser
  dependencies:
    - build-prod-frontend
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/frontend.tar
    - cd frontend
  script:
    - docker tag $DOCKER_IMAGE_FRONTEND "$CI_REGISTRY"/"$CI_PROJECT_PATH"/frontend:$CI_COMMIT_SHA
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH"/frontend:$CI_COMMIT_SHA
  only:
    - develop
    - master

tag-frontend-branch:
  stage: push-branch
  needs:
    - build-prod-frontend
    - test-frontend-logic
    - test-frontend-on-browser
  dependencies:
    - build-prod-frontend
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/frontend.tar
    - cd frontend
  script:
    - docker tag $DOCKER_IMAGE_FRONTEND "$CI_REGISTRY"/"$CI_PROJECT_PATH"/frontend:$CI_COMMIT_REF_NAME
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH"/frontend:$CI_COMMIT_REF_NAME
  only:
    - develop
    - master

## SSR Frontend
build-ssr-frontend:
  stage: build
  before_script:
    - mkdir -p tmp_docker_images/ || true
    - cd frontend
  needs: []
  artifacts:
    paths:
      - tmp_docker_images/
    expire_in: 24h # No need to keep it around
  script:
    - docker build --build-arg BUILD_COMMAND=build:ssr -t $DOCKER_IMAGE_FRONTEND  -f scripts/ci-partial-ssr.dockerfile .
    - docker save $DOCKER_IMAGE_FRONTEND -o ../tmp_docker_images/ssr-frontend.tar
  only:
    - develop
    - master

push-ssr-frontend:
  stage: push-commit
  dependencies:
    - build-ssr-frontend
  needs:
    - build-ssr-frontend
    - test-frontend-logic
    - test-frontend-on-browser
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/ssr-frontend.tar
    - cd frontend
  script:
    - docker tag $DOCKER_IMAGE_FRONTEND "$CI_REGISTRY"/"$CI_PROJECT_PATH"/frontend-ssr:$CI_COMMIT_SHA
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH"/frontend-ssr:$CI_COMMIT_SHA
  only:
    - develop
    - master

tag-ssr-frontend-branch:
  stage: push-branch
  dependencies:
    - build-ssr-frontend
  needs:
    - build-ssr-frontend
    - test-frontend-logic
    - test-frontend-on-browser
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/ssr-frontend.tar
    - cd frontend
  script:
    - docker tag $DOCKER_IMAGE_FRONTEND "$CI_REGISTRY"/"$CI_PROJECT_PATH"/frontend-ssr:$CI_COMMIT_REF_NAME
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH"/frontend-ssr:$CI_COMMIT_REF_NAME
  only:
    - develop
    - master

## Programaker Frontend
build-programaker-frontend:
  stage: build
  before_script:
    - mkdir -p tmp_docker_images/ || true
    - cd frontend
  needs: []
  artifacts:
    paths:
      - tmp_docker_images/
    expire_in: 24h # No need to keep it around
  script:
    - docker build --build-arg BUILD_COMMAND=build-programaker -t $DOCKER_IMAGE_FRONTEND  -f scripts/ci-partial.dockerfile .
    - docker save $DOCKER_IMAGE_FRONTEND -o ../tmp_docker_images/programaker-frontend.tar
  only:
    - develop
    - master

push-programaker-frontend:
  stage: push-commit
  dependencies:
    - build-programaker-frontend
  needs:
    - build-programaker-frontend
    - test-frontend-logic
    - test-frontend-on-browser
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/programaker-frontend.tar
    - cd frontend
  script:
    - docker tag $DOCKER_IMAGE_FRONTEND "$CI_REGISTRY"/"$CI_PROJECT_PATH"/programaker-frontend:$CI_COMMIT_SHA
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH"/programaker-frontend:$CI_COMMIT_SHA
  only:
    - develop
    - master

tag-programaker-frontend-branch:
  stage: push-branch
  dependencies:
    - build-programaker-frontend
  needs:
    - build-programaker-frontend
    - test-frontend-logic
    - test-frontend-on-browser
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images/programaker-frontend.tar
    - cd frontend
  script:
    - docker tag $DOCKER_IMAGE_FRONTEND "$CI_REGISTRY"/"$CI_PROJECT_PATH"/programaker-frontend:$CI_COMMIT_REF_NAME
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH"/programaker-frontend:$CI_COMMIT_REF_NAME
  only:
    - develop
    - master

## Backend
test-backend:
  stage: test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd backend
  script:
    - docker build -t $DOCKER_IMAGE_BACKEND -f scripts/ci-partial.dockerfile .
    - docker run -t --rm $DOCKER_IMAGE_BACKEND rebar3 eunit

dialyze-backend:
  stage: test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd backend
  script:
    - docker build -t $DOCKER_IMAGE_BACKEND -f scripts/ci-partial.dockerfile .
    - docker run -t --rm $DOCKER_IMAGE_BACKEND rebar3 dialyzer

build-backend:
  stage: build
  needs: []
  artifacts:
    paths:
      - tmp_docker_images_optimized/
    expire_in: 24h # No need to keep it around
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - mkdir -p tmp_docker_images_optimized/ || true
    - cd backend
  script:
    - docker build -t $DOCKER_IMAGE_BACKEND -f scripts/ci-partial.dockerfile .
    - sh ../utils/ci-preparations/optimize-backend-image.sh $DOCKER_IMAGE_BACKEND $DOCKER_IMAGE_BACKEND_OPTIMIZED
    # Run sanity check
    - docker run -t --rm $DOCKER_IMAGE_BACKEND_OPTIMIZED /app/release/bin/automate escript ../scripts/sanity_check.erl
    - docker save $DOCKER_IMAGE_BACKEND_OPTIMIZED -o ../tmp_docker_images_optimized/backend-optimized.tar

api-test-backend:
  stage: e2e-test
  dependencies:
    - build-backend
  needs:
    - build-backend
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images_optimized/backend-optimized.tar
  script:
    - apk add --no-cache curl py3-pip graphviz-dev gcc musl-dev
    - CI_TYPE=gitlab sh utils/testing/run-api-test.sh $DOCKER_IMAGE_BACKEND_OPTIMIZED

push-backend:
  stage: push-commit
  dependencies:
    - build-backend
  needs:
    - build-backend
    - api-test-backend
    - test-backend
    - dialyze-backend
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images_optimized/backend-optimized.tar
    - cd backend
  script:
    - docker tag $DOCKER_IMAGE_BACKEND_OPTIMIZED "$CI_REGISTRY"/"$CI_PROJECT_PATH"/backend:$CI_COMMIT_SHA
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH"/backend:$CI_COMMIT_SHA
  only:
    - develop
    - master

tag-backend-branch:
  stage: push-branch
  dependencies:
    - build-backend
  needs:
    - build-backend
    - api-test-backend
    - test-backend
    - dialyze-backend
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load -i tmp_docker_images_optimized/backend-optimized.tar
    - cd backend
  script:
    - docker tag $DOCKER_IMAGE_BACKEND_OPTIMIZED "$CI_REGISTRY"/"$CI_PROJECT_PATH"/backend:$CI_COMMIT_REF_NAME
    - docker push "$CI_REGISTRY"/"$CI_PROJECT_PATH"/backend:$CI_COMMIT_REF_NAME
  only:
    - develop
    - master
