# See https://docs.docker.com/compose/compose-file/
version: '3'

services:
  programaker-router:
    build: utils/router
    ports:
      - 8080:80
    links:
      - programaker-frontend
      - programaker-backend
    environment:
      - FRONTEND_NODE=programaker-frontend
      - FRONTEND_PORT=80
      - BACKEND_NODE=programaker-backend
      - BACKEND_PORT=8888

  programaker-frontend:
    build: frontend

  programaker-backend:
    build: backend
    hostname: programaker-backend-single
    volumes:
      - programaker-dev-backend-mnesia:/app/mnesia

volumes:
  programaker-dev-backend-mnesia:
