# See https://docs.docker.com/compose/compose-file/
version: '3'

services:
  plaza-router:
    build: utils/router
    ports:
      - 8080:80
    links:
      - plaza-frontend
      - plaza-backend
    environment:
      - FRONTEND_NODE=plaza-frontend
      - FRONTEND_PORT=80
      - BACKEND_NODE=plaza-backend
      - BACKEND_PORT=8888

  plaza-frontend:
    build: frontend

  plaza-backend:
    build: backend
    hostname: plaza-backend-single
    volumes:
      - plaza-dev-backend-mnesia:/app/mnesia

volumes:
  plaza-dev-backend-mnesia:

