# See https://docs.docker.com/compose/compose-file/
version: '3'

services:
  blackbox-exporter:
    build: blackbox-exporter
    restart: always

  prometheus:
    build: prometheus
    restart: always
    links:
      - blackbox-exporter
    ports:
      - 9090:9090
    volumes:
      - plaza-monitoring-prometheus:/prometheus

  grafana:
    build: grafana
    restart: always
    ports:
      - 3000:3000
    links:
      - prometheus
    volumes:
      - plaza-monitoring-grafana:/var/lib/grafana

volumes:
  plaza-monitoring-grafana:
  plaza-monitoring-prometheus:
